### ISSUE TITLE
[Milestone 3] Set up a github page for the project and add basic content

### ISSUE THREAD

**Issue by katoss** [PeerProducedResearch/design-practices#3]
I plan to publish the resource with github pages, because it makes it easy for anyone with a github account to add and update blog posts and source code.

- [x] research possible templates
- [x] set up the page with the basic template
- [x] if necessary, adapt the template so it fulfills the minimum requirements of my concept
- [x] add first 5 blog posts
- [x] add other necessary content (e.g. "about", "contribution guidelines")
